stages:
  date_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
     - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
     - artifacts/prepare_base_model

  model_training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_training.py
      - src/cnnClassifier/componemts/prapare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
     - artifacts/training/model.h5
